<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
<!-- <br /> <input type="button" value="reset（危险！重置所有用户信息！插入测试数据！）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/raz'" /> -->

<hr />

<br /> <input type="button" value="semaine 1（发送第一周邮件a）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/semaine/?week=1'" />
<br /> <input type="button" value="semaine 2（发送第二周邮件a）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/semaine/?week=2'" />
<br /> <input type="button" value="semaine 3（发送第三周邮件a）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/semaine/?week=3'" />
<br /> <input type="button" value="semaine 4（发送第四周邮件a）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/semaine/?week=4'" />
<br /> <input type="button" value="semaine 5（发送第五周邮件a）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/semaine/?week=5'" />

<hr />

<br /> <input type="button" value="relance 1（发送第一周邮件b）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/relance/?week=1'" />
<br /> <input type="button" value="relance 2（发送第二周邮件b）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/relance/?week=2'" />
<br /> <input type="button" value="relance 3（发送第三周邮件b）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/relance/?week=3'" />
<br /> <input type="button" value="relance 4（发送第四周邮件b）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/relance/?week=4'" />
<br /> <input type="button" value="relance 5（发送第五周邮件b）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/relance/?week=5'" />


<hr />

<h1>第二周每天都发youtube视频</h1>

<br /> <input type="button" value="clip semaine 2 jour 1（第一天视频）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/youtube/?day=1'" />
<br /> <input type="button" value="clip semaine 2 jour 2（第二天视频）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/youtube/?day=2'" />
<br /> <input type="button" value="clip semaine 2 jour 3（第三天视频）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/youtube/?day=3'" />
<br /> <input type="button" value="clip semaine 2 jour 4（第四天视频）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/youtube/?day=4'" />
<br /> <input type="button" value="clip semaine 2 jour 5（第五天视频）" onclick="javascript:window.location.href='<?php echo $this->webhost; ?>/admin/emails/youtube/?day=5'" />
</body>
</html>