<input type="button" value="reset" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/raz'" />

<input type="button" value="semaine 1" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/semaine/?week=1'" />
<input type="button" value="semaine 2" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/semaine/?week=2'" />
<input type="button" value="semaine 3" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/semaine/?week=3'" />
<input type="button" value="semaine 4" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/semaine/?week=4'" />
<input type="button" value="semaine 5" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/semaine/?week=5'" />

<input type="button" value="relance 1" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/relance/?week=1'" />
<input type="button" value="relance 2" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/relance/?week=2'" />
<input type="button" value="relance 3" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/relance/?week=3'" />
<input type="button" value="relance 4" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/relance/?week=4'" />
<input type="button" value="relance 5" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/relance/?week=5'" />

<input type="button" value="clip semaine 2 jour 1" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/youtube/?day=1'" />
<input type="button" value="clip semaine 2 jour 2" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/youtube/?day=2'" />
<input type="button" value="clip semaine 2 jour 3" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/youtube/?day=3'" />
<input type="button" value="clip semaine 2 jour 4" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/youtube/?day=4'" />
<input type="button" value="clip semaine 2 jour 5" onclick="javascript:window.location.href='http://preview-evbbcoaches.digitalfactory.pro/admin/emails/youtube/?day=5'" />
