<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>

<pre>
<h1>显示 [ <?php echo $this->log; ?> ]</h1>
<table width="800" border="1" cellpadding="1" cellspacing="1" style="border: 1px solid black;">
  <tr>
    <th width="30%">时间</th>
    <th width="70%"><?php echo ($this->log == 'error') ? '错误':'报告'; ?></th>
  </tr>
  <?php foreach ($this->datas as $result): ?>
  <tr>
    <td align="center"><?php echo $result->date; ?></td>
    <td><?php echo $result->content; ?></td>
  </tr>
  <?php endforeach; ?>
</table></pre>
</body>
</html>